name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker image
      run: docker-compose build

    - name: Test
      run: |
        docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test